apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oisp-test-sensor
  namespace: oisp-devices
  labels:
    app: oisp-test-sensor
spec:
  selector:
    matchLabels:
      app: oisp-test-sensor
  template:
    metadata:
      labels:
        app: oisp-test-sensor
    spec:
      containers:
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                name: oisp-device-secret
                key: activationCode
        image: wagmarcel/oisp-iot-agent:devel
        imagePullPolicy: IfNotPresent
      nodeSelector:
        deviceType: iot