apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oisp-test-sensor
  namespace: oisp-devices
  labels:
    app: oisp-test-sensor
spec:
  selector:
    matchLabels:
      app: oisp-test-sensor
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oisp-test-sensor
    spec:
      containers:
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                name: oisp-devices-secret
                key: activationCode
        volumeMounts:
          - name: oisp-device-config-volume
            mountPath: /volume/config
          - name: oisp-device-data-volume
            mountPath: /volume/data
        image: wagmarcel/oisp-iot-agent:latest
        imagePullPolicy: IfNotPresent
      - name: oisp-testsensor
        image: wagmarcel/oisp-testsensor:latest
        resources:
          limits:
            net.oisp/testdevice: 1
      volumes:
        - name: oisp-device-config-volume
          configMap:
            name: oisp-devices-config
        - name: oisp-device-data-volume
          persistentVolumeClaim:
            claimName: device-data
      nodeSelector:
        deviceType: iot