apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oisp-test-sensor
  namespace: oisp-devices
  labels:
    app: oisp-test-sensor
spec:
  selector:
    matchLabels:
      app: oisp-test-sensor
  template:
    metadata:
      labels:
        app: oisp-test-sensor
    spec:
      containers:
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: OISP_DEVICE_ACTIVATION_CODE
        valueFrom:
          secretKeyRef:
            name: oisp-devices-secret
            key: activationCode
        volumeMounts:
          - name: oisp-device-config-volume
            mountPath: /var/config
        image: wagmarcel/oisp-iot-agent:latest
        imagePullPolicy: IfNotPresent
      - name: oisp-testsensor
        image: wagmarcel/oisp-testsensor:latest
        resources:
          limits:
            net.oisp/testdevice: 1
      volumes:
        - name: oisp-device-config-volume
          configMap:
            name: oisp-devices-config
      nodeSelector:
        deviceType: iot