apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oisp-test-sensor
  namespace: oisp-devices
  labels:
    app: oisp-test-sensor
spec:
  selector:
    matchLabels:
      app: oisp-test-sensor
  template:
    metadata:
      labels:
        app: oisp-test-sensor
    spec:
      containers:
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: wagmarcel/oisp-iot-agent:devel
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: sysfs
          mountPath: /sys
        - name: kubeletsockets
          mountPath: /var/lib/rancher/k3s/agent/kubelet/device-plugins/
      nodeSelector:
        deviceType: iot
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sysfs
        hostPath:
          path: /sys
      - name: kubeletsockets
        hostPath:
          path: /var/lib/rancher/k3s/agent/kubelet/device-plugins/
